name: git issues blog workflow

on: 
  push:
    branches:
      - develop
    paths:
      - 'posts/*.md'
      - 'posts/*/*.md'
      - 'posts/*/*/*.md'

jobs:
  git-issues-blog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: develop
    - name: Git-Issues-Blog
      uses: Sep0lkit/git-issues-blog@v1.3
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        POSTS_PATH: 'posts'